apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-server
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-server
  template:
    metadata:
      labels:
        app: admin-server
    spec:
      containers:
        - name: admin-server
          image: {{ .Values.adminServer.image }}:{{ .Values.adminServer.tag }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.adminServer.port }}
          env:
            - name: SERVER_PORT
              value: "{{ .Values.adminServer.port }}"
            - name: CONFIG_SERVER_URL
              value: "http://config-server:8888/"
            - name: SPRING_CLOUD_EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://discovery-server:8761/eureka/"
---
apiVersion: v1
kind: Service
metadata:
  name: admin-server
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: admin-server
  ports:
    - port: {{ .Values.adminServer.port }}
      targetPort: {{ .Values.adminServer.port }}
