apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      # Init container waits for Eureka to be ready
      initContainers:
        - name: wait-for-eureka
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              echo "Waiting for Eureka..."
              until nc -z discovery-server.petclinic.svc.cluster.local 8761; do
                echo "Eureka not ready, sleeping 2s..."
                sleep 2
              done
              echo "Eureka is up!"
      containers:
        - name: api-gateway
          image: {{ .Values.api-gateway.image }}:{{ .Values.api-gateway.tag }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.api-gateway.port }}
          env:
            - name: SERVER_PORT
              value: "{{ .Values.api-gateway.port }}"
            - name: CONFIG_SERVER_URL
              value: "http://config-server:8888/"
            - name: SPRING_CLOUD_EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://discovery-server.petclinic.svc.cluster.local:8761/eureka/
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.api-gateway.port }}
            initialDelaySeconds: 10
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: petclinic
spec:
  selector:
    app: api-gateway
  ports:
    - port: {{ .Values.api-gateway.port }}
      targetPort: {{ .Values.api-gateway.port }}