apiVersion: apps/v1
kind: Deployment
metadata:
  name: customers-service
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customers-service
  template:
    metadata:
      labels:
        app: customers-service
    spec:
      containers:
        - name: customers-service
          image: {{ .Values.customers-service.image }}:{{ .Values.customers-service.tag }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.customers-service.port }}
          env:
            - name: CONFIG_SERVER_URL
              value: "http://config-server:8888/"
---
apiVersion: v1
kind: Service
metadata:
  name: customers-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: customers-service
  ports:
    - port: {{ .Values.customers-service.port }}
      targetPort: {{ .Values.customers-service.port }}
