apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-server
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-server
  template:
    metadata:
      labels:
        app: discovery-server
    spec:
      containers:
        - name: discovery-server
          image: {{ .Values.discoveryServer.image }}:{{ .Values.discoveryServer.tag }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.discoveryServer.port }}
          env:
          - name: SERVER_PORT
            value: "{{ .Values.discoveryServer.port }}"
          - name: CONFIG_SERVER_URL
            value: "http://config-server:8888/"
          - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
            value: "false"
          - name: EUREKA_CLIENT_FETCH_REGISTRY
            value: "false"
          - name: EUREKA_INSTANCE_HOSTNAME
            value: "discovery-server"
---
apiVersion: v1
kind: Service
metadata:
  name: discovery-server
  namespace: petclinic
spec:
  selector:
    app: discovery-server
  ports:
    - port: {{ .Values.discoveryServer.port }}
      targetPort: {{ .Values.discoveryServer.port }}
