apiVersion: apps/v1
kind: Deployment
metadata:
  name: genai-service
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: genai-service
  template:
    metadata:
      labels:
        app: genai-service
    spec:
      containers:
        - name: genai-service
          image: {{ .Values.genai-service.image }}:{{ .Values.genai-service.tag }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.genai-service.port }}
          env:
           - name: CONFIG_SERVER_URL
             value: "http://config-server:8888/"
       
---
apiVersion: v1
kind: Service
metadata:
  name: genai-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: genai-service
  ports:
    - port: {{ .Values.genai-service.port }}
      targetPort: {{ .Values.genai-service.port }}
