apiVersion: apps/v1
kind: Deployment
metadata:
  name: vets-service
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vets-service
  template:
    metadata:
      labels:
        app: vets-service
    spec:
      containers:
        - name: vets-service
          image: {{ .Values.vets-service.image }}:{{ .Values.vets-service.tag }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.vets-service.port }}
          env:
          - name: CONFIG_SERVER_URL
            value: "http://config-server:8888/"
---
apiVersion: v1
kind: Service
metadata:
  name: vets-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: vets-service
  ports:
    - port: {{ .Values.vets-service.port }}
      targetPort: {{ .Values.vets-service.port }}